import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ThemeProviderWrapper } from "./context/ThemeContext";
import { LanguageProvider } from "./context/LanguageContext";
import { Box } from "@mui/material";
import { FileX } from "lucide-react";

export const metadata: Metadata = {
  title: "Math",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ margin: 0, padding: 0 }}>
        <ThemeProviderWrapper>
          <LanguageProvider>
            <Box
              sx={{
                display: "flex",
                flexDirection: "column",
                minHeight: "100vh",
              }}
            >
              <Header />
              <Box component="main" sx={{ flexGrow: 1 ,marginTop:10,display:"flex",justifyContent:"center"}}>
                {children}
              </Box>
              <Footer />
            </Box>
          </LanguageProvider>
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
