import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ThemeProviderWrapper } from "./context/ThemeContext";
import { LanguageProvider } from "./context/LanguageContext";

export const metadata: Metadata = {
  title: "Math",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProviderWrapper>
        <LanguageProvider>

          <Header />
          {children}
          </LanguageProvider>
        </ThemeProviderWrapper>
        <Footer />
      </body>
    </html>
  );
}
